# Generated by Django 3.0.7 on 2020-09-27 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='created_date',
            new_name='date_created',
        ),
    ]
